# This GitHub Actions workflow is designed for a Node.js application.
# It performs the following tasks on every commit:
# 1. Runs unit tests.
# 2. Performs SonarQube scanning.
# 3. Builds a Docker image.
# 4. Scans the Docker image for vulnerabilities using Trivy.
# 5. Pushes the Docker image to a Docker registry.

name: CI Pipeline

on:
  push:
    branches:
      - '**' # Triggers on every branch commit.

jobs:
  

  

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: "sandhya0593"# Replace with your DockerHub username
          password: "HDFC@1998lax"# Replace with your DockerHub password

      - name: Build Docker Image
        run: |
          docker build -t sandhya0593/netflix05:latest .

      
      - name: Push Docker Image
        run: |
          docker push sandhya0593/netflix05:latest